site_name: CS Share

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon16x16.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    # - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - md_in_html
