site_name: CS Plan
site_url: https://cs-plan.com
site_author: MingLLuo

repo_name: CS-Plan
repo_url: https://github.com/MingLLuo/CS-Plan
theme:
  name: material
  language: zh
  custom_dir: overrides
  static_templates:
    - 404.html

  features:
    - navigation.instant
    # - navigation.expand
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: light blue
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: indigo
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
  font:
    text: Noto Serif SC  
    code: Roboto Mono

  icon:
    repo: fontawesome/brands/github

extra:
  analytics:
    provider: google
    property: G-6XJGJRLBLZ

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  - attr_list
  - md_in_html
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

nav:
  - 前言: "index.md"
  - CS基础: 
    - 导览: "CS基础/导览.md"
    - 计算机导论:
      - "Crash Course Computer Science": "CS基础/课程推荐/计算机导论/计算机速成课.md"
      -  "Harvard CS50": "CS基础/课程推荐/计算机导论/HarvardCS50.md"
    - 编程基础:
      - "UCB CS61A: Structure and Interpretation of Computer Programs": "CS基础/课程推荐/编程基础/UCBCS61A.md"
      - "其他推荐": "CS基础/课程推荐/编程基础/基础编程资源汇总.md"
    - 数学基础:
      - "MIT18.06: Linear Algebra": "CS基础/课程推荐/数学基础/MITGSLA.md"
      - "UCB CS70: Discrete Mathematics and Probability Theory":  "CS基础/课程推荐/数学基础/UCBDM.md"
    - 算法基础:
      - "UCB CS61B: Data Structures": "CS基础/课程推荐/算法基础/UCBCS61B.md"
    - 工具与策略: "CS基础/工具与策略.md"
  - 基础深入:
    - 深入导览: "基础深入/导览.md"
    - 数学进阶:
      - "概率论专题": "基础深入/课程推荐/数学进阶/Probability.md"
      - "SCNU: A Concrete Introduction to Number Theory and Algebra": "基础深入/课程推荐/数学进阶/CINTA.md"
    - 计算理论:
      - "ITOC: Introduction To The Theory Of Computation": "基础深入/课程推荐/计算理论/ITOC.md"
    - 算法进阶:
      - "UCB CS170: Efficient Algorithms and Intractable Problems": "基础深入/课程推荐/算法进阶/UCBCS170.md"
    - PL:
      - 函数式编程:
        - "CS3110: OCaml Programming Correct + Efficient + Beautiful": "基础深入/课程推荐/PL/函数式编程/CornellCS3110.md"
      - 编译原理:
        - "Modern Compiler Implementation": "基础深入/课程推荐/PL/编译原理/MordernCompilerImpl.md"
      - 编译语言设计和程序分析:
        - "Brown CSCI1260 / UCB CS164 Compilers and Program Analysis:": "基础深入/课程推荐/PL/编译语言设计和程序分析/BrownCSCI1260.md"
    - 体系结构:
      - "UCB CS61C: Great Ideas in Computer Architecture (Machine Structures)": "基础深入/课程推荐/体系结构/UCBCS61C.md"
      - "Brown CSCI0300: Fundamentals of Computer Systems": "基础深入/课程推荐/体系结构/BrownCS0300.md"
    - Systems:
      - 操作系统:
        - "操作系统专题": "基础深入/课程推荐/Systems/操作系统/OS.md"
        - "MIT 6.1810: Operating System Engineering": "基础深入/课程推荐/Systems/操作系统/MIT6.S1810.md"
        - "UCB CS162: Operating Systems and System Programming": "基础深入/课程推荐/Systems/操作系统/UCBCS162.md"
      - 分布式系统:
        - "MIT 6.5840: Distributed Systems": "基础深入/课程推荐/Systems/分布式系统/MIT6.5840.md"
    - 人工智能:
      - "UCB CS188: Introduction to Artificial Intelligence": "基础深入/课程推荐/人工智能/UCBCS188.md"
      - "UMich EECS 498-007 / 598-005: Deep Learning for Computer Vision": "基础深入/课程推荐/深度学习/UMEECS498.md"
    - 计算机安全:
      - 综合:
        - "UCB CS161: Computer Security": "基础深入/课程推荐/计算机安全/综合/UCBCS161.md"
      - 密码学:
        - "Brown CSCI1510: Introduction to Cryptography and Computer Security": "基础深入/课程推荐/计算机安全/密码学/BrownCSCI1510.md"
        - "Brown CSCI1515: Applied Cryptography": "基础深入/课程推荐/计算机安全/密码学/BrownCSCI1515.md"
  - 书籍推荐: 
    - "推荐书目" : "书籍推荐.md"
    - Books:
      - "Operating Systems: Three Easy Pieces" : "books/OSTEP.md"
  - 贡献要求: "贡献方式及要求.md"
  - 后记: "end.md"